export const units = [
    { label: "gram", value: "g" },
    { label: "ounce", value: "oz" },
    { label: "pound", value: "lb" },
    { label: "milliliter", value: "ml" },
    { label: "liter", value: "l" },
    { label: "teaspoon", value: "tsp" },
    { label: "tablespoon", value: "tbsp" },
    { label: "fluid ounce", value: "fl oz" },
    { label: "cup", value: "cup" },
    { label: "milligram", value: "mg" },
    { label: "kilogram", value: "kg" },
    { label: "millimeter", value: "mm" },
    { label: "centimeter", value: "cm" },
    { label: "piece", value: "piece" },
    { label: "pack", value: "pack" },
    { label: "can", value: "can" },
    { label: "bottle", value: "bottle" },
    { label: "jar", value: "jar" },
    { label: "box", value: "box" },
    { label: "bag", value: "bag" },
    { label: "pinch", value: "pinch" },
    { label: "handful", value: "handful" },
    { label: "stick", value: "stick" },
    { label: "slice", value: "slice" },
    { label: "head", value: "head" },
    { label: "bulb", value: "bulb" }
];

export const cups_data = [
    { label: "1", value: "1" },
    { label: "½", value: "½"},
    { label: "⅓", value: "⅓"},
    { label: "¼", value: "¼"},
    { label: "⅛", value: "⅛"},
    { label: "⅔", value: "⅔"},
    { label: "¾", value: "¾"},
];